server {
    listen       8080;
    server_name  _;

    root   /usr/share/nginx/html;
    index  index.html;

    # SPA/MPA fallback: qualquer rota cai no index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache dos estáticos
    location ~* \.(js|jsx|css|png|jpg|jpeg|gif|webp|svg|ico|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }
}
